### ISSUE TITLE
external volume "caddy_data" not found

### ISSUE THREAD

**Issue by sakarimov** [detche/docker-websvn#1]
i want to try this project, but when i try to compose from https/ directory, i got this error

```
$ docker compose up
external volume "caddy_data" not found
```
i change the ```caddy_data``` to directory i want, and then i got this error, do i miss some step to make it run?

**Comment by detche** [comment]
Hello @sakarimov, sorry I should have added some documentation on that part.

I have added this section in both samples README file:

> # Running the sample
> * Create the caddy_data volume for persistent HTTPS data: `sudo docker volume create caddy_data`,
> * Start the services: `sudo docker compose up -d`

Indeed, the [caddy docker image](https://hub.docker.com/_/caddy) instructs to use an external volume for its data:

> Defining the data volume as [external](https://docs.docker.com/compose/compose-file/compose-file-v3/#external) makes sure `docker-compose down` does not delete the volume. You may need to create it manually using  `docker volume create caddy_data`.

Let me know if you encounter further issues.
